[general]
import = [
    "~/.config/alacritty/papercolor_light.toml",
    # "C:/Users/NilsCarlson/AppData/Roaming/alacritty/selenized_light.toml"
]

[window]
decorations = "None"
dimensions = { columns = 130, lines = 30 }
position = { x = 100, y = 30 }
opacity = 0.98

[colors]
cursor = { text = "CellBackground", cursor = "#000000" }

[cursor]
style = { shape = "Underline", blinking = "Off" }

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 14
